### ISSUE TITLE
RxSBasicSegment has no attribute cbw

### ISSUE THREAD

**Issue by DerBambus** [Gi-z/CSIKit#37]
Hi there,
I have some measurements using Picoscenes with two usrp n210 devices, however when I try parsing them with csikit, I get the following error:
![Screenshot_20230324_131050](https://user-images.githubusercontent.com/33605989/227518218-44cb5dd4-845f-4729-a11e-399d269ee364.png)
I am using the example code provided in the readme, and when I try and parse an example file py picoscenes it correctly reads the data in. Any Ideas on what this issue might be?

**Comment by leonhorn99** [comment]
Hi, did you find a solution for this?

**Comment by Gi-z** [comment]
Provide an example of a file that causes this error and I'll look at getting it fixed asap.

**Comment by leonhorn99** [comment]
[csifile.zip](https://github.com/Gi-z/CSIKit/files/15009081/csifile.zip)

This is a file recorded with picoscenes from a IWL5300 nic

Thanks a lot!

**Comment by leonhorn99** [comment]
Okay, i was able to narrow it down a bit:
There is now dictionary entry for version = 4 in the __init__ function of RxSBasic, as well as no parse funktion. Thats why the parameters (like cbw) are not initialized.
Since I have no real knowledge of the meaning of these bytes, I can't really contribute any further unfortunatly.

The function AbstractPicoScenesFrameSegment.read_header() assigns the 4. This might be the bug?

Thank you, Leon

**Comment by Gi-z** [comment]
> I am still not sure what this version number is referring to, but after some digging in the parsing kernel and validating with the byte sequence i wrote a parsev4. This is the updated file, everything else is left as is. The only change was the addition of another 64 bit timestamp after the first one.
> 
> [RxSBasicSegment.zip](https://github.com/Gi-z/CSIKit/files/15011435/RxSBasicSegment.zip)

You should be able to install with the latest commit using: `pip install git+https://github.com/Gi-z/CSIKit.git`. Let me know if that works for you and I'll look at deploying to pip.

**Comment by saurlax** [comment]
@Gi-z same error, on both Windows and Ubuntu 22.04

Sample: [rx_2_250418_135838.zip](https://github.com/user-attachments/files/19810621/rx_2_250418_135838.zip)

```powershell
> csikit .\rx_2_250418_135838.csi
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Scripts\csikit.exe\__main__.py", line 7, in <module>
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\__main__.py", line 62, in main
    display_info(args.file, args.scaled, args.filter_mac)
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\tools\get_info.py", line 7, in display_info
    csi_data = reader.read_file(path, scaled=scaled, filter_mac=filter_mac)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\reader\readers\read_pico.py", line 93, in read_file
    ret_data.bandwidth = frame_container.get_bandwidth()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\reader\readers\pico\FrameContainer.py", line 38, in get_bandwidth
    return self.RxSBasic.cbw
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RxSBasicSegment' object has no attribute 'cbw'
```

`pip install git+https://github.com/Gi-z/CSIKit.git` also doesn't work:

```powershell
> csikit .\rx_2_250418_135838.csi
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Scripts\csikit.exe\__main__.py", line 7, in <module>
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\__main__.py", line 60, in main
    from CSIKit.tools.get_info import display_info
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\tools\get_info.py", line 2, in <module>
    from CSIKit.reader import get_reader
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\reader\__init__.py", line 3, in <module>
    from CSIKit.reader.readers.read_atheros import ATHBeamformReader
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\reader\readers\read_atheros.py", line 6, in <module>
    from CSIKit.csi import CSIData
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\csi\__init__.py", line 3, in <module>
    from CSIKit.csi.frames.iwl import IWLCSIFrame
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\csi\frames\__init__.py", line 2, in <module>
    from CSIKit.csi.frames.esp import ESP32CSIFrame
  File "C:\Users\saurl\AppData\Local\Programs\Python\Python311\Lib\site-packages\CSIKit\csi\frames\esp.py", line 175
    self.mac = f"00:16:ea:{":".join(csv_line[0].split())}"
                            ^
SyntaxError: f-string: expecting '}'
```

**Comment by saurlax** [comment]
@Gi-z `pip install git+https://github.com/Gi-z/CSIKit.git@6ac8cefd4ca2831b7439735965fd7e5822345419` works well for me. It seems that the previous error is caused by other newly question. It would be great if you could send this version to pypi. Thank you very much!
